apiVersion: v1
kind: Service
metadata:
  name: python-app
spec:
  selector:
    app: python-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: backend
        image: gcr.io/$PROJECT_ID/python-app:$SHORT_SHA
        env:
        - name: DB_HOST
          value: "104.197.86.70"
        - name: DB_NAME
          value: "myappdb"
        - name: DB_USER
          value: "rama"
        - name: DB_PASSWORD
          value: "admin"
        ports:
        - containerPort: 5000